### ISSUE TITLE
Major issue with passing weights to changepoints from segment

### ISSUE THREAD

**Issue by gh-spavlov** [veseshan/DNAcopy#9]
@veseshan The main segment() function calls changepoints() on genomdati[chromi == ic], meaning it restricts the data to one chromosome at a time. However, the same call to changepoints() takes in the entire weights vector (wghts = weights[ina]) for all probes, and does not subset it to the same chromosome to which the genomic data belongs. Within the changepoints function, indexing is done from seg.end, which always begins with elements c(0,length(genomdat)), meaning weights from the beginning of the weights vector are taken. This results in incorrect weights being used for all chromosomes other than chr1, potentially leading to incorrect segmentation for these chromosomes.

A simple fix would be to index wghts[chromi == ic] when calling changepoints() from segment() - this way, each chromosome gets its corresponding weights from the weights vector. 

Please let me know if anything about this explanation is unclear, or if I have overlooked something in the code.

**Comment by gh-spavlov** [comment]
Hi @veseshan, wanted to make sure you saw this post because I did not tag you when I first opened the issue - thanks.

**Comment by veseshan** [comment]
You may be right and your proposed fix will take car of it. Thankfully it only affects the weighted segmentation and using incorrect weights will most likely reduce the power to detect changepoints which will have an impact only on borderline cases. Thank you.

**Comment by veseshan** [comment]
Fix uploaded here and to devel branch
